### ISSUE TITLE
save interim L3? 

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#12]
Right now, the interpolation of L2 takes the longest on the way from L1 to L3 would it be usefull to save a 'interim L3' that contains the interpolated sondes for one flight and then concatenate them whenever a new flight is added.

Option 2 would be to check for each flight whether it's already in the L3 data and then only run the processing for the ones that are not. Then we'd need a concatenation and trust that people are using the same processing for all flights. 

Maybe it's also not too bad (in flight, we can do the processing just on a folder with one flight and in the end of the campaign we will have to run the whole pipeline on everything anyway.

**Comment by Geet-George** [comment]
Hi @hgloeckner, yes, this is exactly [what JOANNE does](https://github.com/Geet-George/JOANNE/blob/d0d96fc29abbd4840a303a426786e1114138eb92/joanne/Level_3/fn_3.py#L876). It creates interim files for every sonde that are interpolated (there are many steps in there) and ready to be concatenated. Then it keeps saving these interim files as cache. Note that, the interim files are saved with the current version of the package, so if there are any changes in the code, the interim files will be recreated and saved again, not reused from older versions. This is by design. So, it is cache with a caveat.
