### ISSUE TITLE
quality control Level3

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#55]
I just realized that in Level_3 there are some sondes with very low IWV. Do we want them in Level3? I guess those are some with missing values or where something went wrong in some regions. We might consider marking them as 'UGLY' or 'BAD' (I cannot remember which was the better label) in the yaml and remove them from the level_3? What do you think?

**Comment by Geet-George** [comment]
Ideally the checks take place between L1 and L2, where sondes are marked `GOOD`, `BAD` or `UGLY`. Depending on what the problem is (i.e. fewer measurements in the profile, or errors in humidity measurements), the quality flags will change for the individual tests and subsequently an overall flag for the sonde. You can find an overview in [Table 5 in the JOANNE paper](https://essd.copernicus.org/articles/13/5253/2021/). For JOANNE, we only passed the `GOOD` sondes from L1 to L2. 

For the broad difference between `UGLY` and `BAD`, I quote from the paper, "_A sounding's success in the QC stage is provided by a parameter `qc_flag`, which has possible values of good, bad and ugly. The values stand for fully usable, non-usable and partially usable data, respectively, and are described in more detail later with relevant context._"

**Comment by Geet-George** [comment]
> I guess those are some with missing values or where something went wrong in some regions. 

Are all QC tests running? The tests should be able to detect what went wrong with those sondes, i.e. missing values or "bad" values.

**Comment by hgloeckner** [comment]
> > I guess those are some with missing values or where something went wrong in some regions.
> 
> Are all QC tests running? The tests should be able to detect what went wrong with those sondes, i.e. missing values or "bad" values.

I think so, at least the qc flags are added to the attributes of the dataset. But to be honest, I haven't looked into the lev1->lev2 processing too closely.

**Comment by hgloeckner** [comment]
This problem is solved by adding the quality control properly in the config (see #67)
